Task/update others
VitaliyBogdanuk/swidler-quiz-app-server pull request #119
Opened 2023-11-07 17:41 UTC by OleksandrZhelihovskyi

update option developed

2023-11-07 18:01 UTC, VitaliyBogdanuk commented on views/pages/form_cheaterPhone.ejs
> +	if(!updateData) {let updateData};
для чого це?
Я так розумію це костиль для того щоб не крашилась апка через те що рендериться пуста без данних чітера якщо створюємо нового?

2023-11-07 18:03 UTC, VitaliyBogdanuk commented on views/pages/users.ejs
> +                                                <a href="/forms/user/?id=<%= user.id %>&name=<%= user.name %>&email=<%= user.email%>"
прекрасно, це не найкраще рішення передавати сенсетів дату користувача в url

2023-11-07 18:04 UTC, VitaliyBogdanuk commented on views/templates/sidebar.ejs
> -        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
Та можна було і залишити в прнципі тілько лого змінити та слоган

2023-11-07 18:43 UTC, OleksandrZhelihovskyi commented on controllers/cheaterPhoneController.js
> +    try {if (!req.query.phone)
виправив

2023-11-07 18:46 UTC, OleksandrZhelihovskyi commented on controllers/userController.js
> +        return await User.findOne({
Повернув як було

2023-11-07 20:31 UTC, OleksandrZhelihovskyi commented on routes/cheaterPhones.js
> +router.post('/cheaterPhoneAdmin/:id', updateCheaterPhone);
Це ще з хакатону ця тема. Окремо щоб з адмінки додавати і з додатку. Там різні функції

2023-11-07 20:31 UTC, OleksandrZhelihovskyi commented on views/pages/feedbacks.ejs
> -                                                <a href="/feedback/<%= feedback.id %>"
я його не робив. А якщо залишити - викине JSON на екран і буде негарно. Потім треба допрацювати по фронтенду

2023-11-07 20:33 UTC, OleksandrZhelihovskyi commented on views/pages/form_cheaterPhone.ejs
> +	if(!updateData) {let updateData};
це не треба. Забув видалити

2023-11-07 20:34 UTC, OleksandrZhelihovskyi commented on views/pages/users.ejs
> +                                                <a href="/forms/user/?id=<%= user.id %>&name=<%= user.name %>&email=<%= user.email%>"
я розумію, але як інакше? Там нічого кримінального нема. Лише пошта та ім'я

2023-11-07 20:35 UTC, OleksandrZhelihovskyi commented on views/templates/sidebar.ejs
> -        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
наступними ПР щось там придумаю

2023-11-07 20:51 UTC, VitaliyBogdanuk commented on routes/cheaterPhones.js
> +router.post('/cheaterPhoneAdmin/:id', updateCheaterPhone);
Додаток і адмінка мають використовувати взагалі різні роути
для додатка у вас є apiRoutes
відповідно з додатку буде /api/cheaterPhone/:id
а з адмінки напряму /cheaterPhone/:id

2023-11-07 20:53 UTC, VitaliyBogdanuk commented on views/pages/feedbacks.ejs
> -                                                <a href="/feedback/<%= feedback.id %>"
добре, але в такому випадку треба було не видаляти тільки лінку, а видалити або закоментувати повністю іконку і це стосується всіх файлів де ви в цьому місці вносили зміни

2023-11-07 20:54 UTC, VitaliyBogdanuk commented on views/pages/users.ejs
> +                                                <a href="/forms/user/?id=<%= user.id %>&name=<%= user.name %>&email=<%= user.email%>"
пошта використовується для логіна, Імʼя це додаткова підказка для зламу аккаунта.
Так робити не можна і крапка.
можете передати userId а все решта опрацьовуйте в контролері і повертайте на вьюху

2023-11-07 20:55 UTC, VitaliyBogdanuk commented on views/templates/sidebar.ejs
> -        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
не наступним а цим.

2023-11-07 21:15 UTC, OleksandrZhelihovskyi commented on routes/cheaterPhones.js
> +router.post('/cheaterPhoneAdmin/:id', updateCheaterPhone);
виправив

2023-11-07 21:20 UTC, OleksandrZhelihovskyi commented on views/pages/feedbacks.ejs
> -                                                <a href="/feedback/<%= feedback.id %>"
закоментив

2023-11-07 21:27 UTC, VitaliyBogdanuk commented on routes/cheaterPhones.js
> +router.post('/cheaterPhoneAdmin/:id', updateCheaterPhone);
не бачу коміта

2023-11-07 21:27 UTC, VitaliyBogdanuk commented on views/pages/feedbacks.ejs
> -                                                <a href="/feedback/<%= feedback.id %>"
не бачу коміта

2023-11-07 21:59 UTC, OleksandrZhelihovskyi commented on views/pages/users.ejs
> +                                                <a href="/forms/user/?id=<%= user.id %>&name=<%= user.name %>&email=<%= user.email%>"
виправив

2023-11-07 22:12 UTC, OleksandrZhelihovskyi commented on views/templates/sidebar.ejs
> -        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
виправив

2023-11-07 22:29 UTC, VitaliyBogdanuk requested changes
@OleksandrZhelihovskyi

2023-11-07 22:29 UTC, VitaliyBogdanuk commented on controllers/userController.js
> -            attributes: ['id', 'name', 'email', /* other user fields you need */],
поверніть ці атрибути, інакше ви будете повертати з бази всі данні разом з паролем користувача.

2023-11-07 22:29 UTC, VitaliyBogdanuk commented on models/topic.js
> +        Topic.belongsToMany(models.User, {
ви пробували витягнути Юзера з якимось закіченими топіками?
Нам по суті потрібно знати тільки ід цих топіків. а у вашому варіанті це буде простиня разом з усіма тестами цього топіку та відповідями

2023-11-07 22:29 UTC, VitaliyBogdanuk commented on views/pages/achievements.ejs
> +                                                <a href="/forms/achievement/?id=<%= achievement.id %>&title=<%= achievement.title %>&image=<%= achievement.image %>&scoreRequired=<%= achievement.score
повторюсь не передавайте дані через url, це не безпечно і в цьому тут не має необхідності

2023-11-07 22:29 UTC, VitaliyBogdanuk commented on views/pages/answers.ejs
>                                                  <a href="/forms/answer/?id=<%= answer.id %>&text=<%= answer.text %>"
повторюсь не передавайте дані через url, це не безпечно і в цьому тут не має необхідності

2023-11-07 22:29 UTC, VitaliyBogdanuk commented on views/pages/categories.ejs
>                                                  <a href="/forms/category/?id=<%= category.id %>&title=<%= category.title %>"
повторюсь не передавайте дані через url, це не безпечно і в цьому тут не має необхідності

2023-11-07 22:29 UTC, VitaliyBogdanuk commented on views/pages/cheaterPhones.ejs
> +                                                <a href="/forms/cheaterPhone/?id=<%= cheaterPhone.id %>&phone=<%= cheaterPhone.phone %>&userId=<%= cheaterPhone.userId%>"
повторюсь не передавайте дані через url, це не безпечно і в цьому тут не має необхідності

2023-11-07 22:29 UTC, VitaliyBogdanuk commented on views/pages/situations.ejs
> +                                                <a href="/forms/situation/?id=<%= situation.id %>&question=<%= situation.question %>&wrongAnswerDescription=<%= situation.wrongAnswerDescription%>"
повторюсь не передавайте дані через url, це не безпечно і в цьому тут не має необхідності

2023-11-07 22:29 UTC, VitaliyBogdanuk commented on views/pages/topics.ejs
> +                                                <a href="/forms/topic/?id=<%= topic.id %>&title=<%= topic.title %>&description=<%= topic.description%>"
повторюсь не передавайте дані через url, це не безпечно і в цьому тут не має необхідності

2023-11-07 22:29 UTC, VitaliyBogdanuk commented on views/templates/sidebar.ejs
> +            <span class="ms-1 font-weight-bold text-white">Login page</span>
Яким боком тут опинився Login page? Просто залишіть як було, змініть тільки логотип і все.

2023-11-07 22:37 UTC, OleksandrZhelihovskyi commented on models/topic.js
> +        Topic.belongsToMany(models.User, {
{
    "id": 1,
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "$2y$10$n/tuZdErwQ4f01ug0qhiv.c1qqBY19xEkwkTlgs3NBz3yg2vfcWse",
    "authProvider": "google",
    "score": 100,
    "correctAnswersCount": 0,
    "wrongAnswersCount": 0,
    "finishedTopics": [
        {
            "id": 1
        },
        {
            "id": 5
        }
    ]
}

2023-11-07 22:42 UTC, OleksandrZhelihovskyi commented on controllers/userController.js
> -            attributes: ['id', 'name', 'email', /* other user fields you need */],
виправив

2023-11-07 22:47 UTC, OleksandrZhelihovskyi commented on views/pages/achievements.ejs
> +                                                <a href="/forms/achievement/?id=<%= achievement.id %>&title=<%= achievement.title %>&image=<%= achievement.image %>&scoreRequired=<%= achievement.score
виправив

2023-11-07 22:58 UTC, OleksandrZhelihovskyi commented on views/pages/answers.ejs
>                                                  <a href="/forms/answer/?id=<%= answer.id %>&text=<%= answer.text %>"
виправив

2023-11-07 23:05 UTC, VitaliyBogdanuk commented on models/topic.js
> +        Topic.belongsToMany(models.User, {
супер але навіщо нам повертати це:
"password": "$2y$10$n/tuZdErwQ4f01ug0qhiv.c1qqBY19xEkwkTlgs3NBz3yg2vfcWse",
"authProvider": "google",

2023-11-07 23:18 UTC, VitaliyBogdanuk requested changes

2023-11-07 23:18 UTC, VitaliyBogdanuk commented on controllers/userController.js
> -            attributes: ['id', 'name', 'email', /* other user fields you need */],
не бачу коміта

2023-11-07 23:39 UTC, OleksandrZhelihovskyi commented on views/pages/topics.ejs
> +                                                <a href="/forms/topic/?id=<%= topic.id %>&title=<%= topic.title %>&description=<%= topic.description%>"
виправив

2023-11-07 23:39 UTC, OleksandrZhelihovskyi commented on views/pages/situations.ejs
> +                                                <a href="/forms/situation/?id=<%= situation.id %>&question=<%= situation.question %>&wrongAnswerDescription=<%= situation.wrongAnswerDescription%>"
виправив

2023-11-07 23:39 UTC, OleksandrZhelihovskyi commented on views/pages/cheaterPhones.ejs
> +                                                <a href="/forms/cheaterPhone/?id=<%= cheaterPhone.id %>&phone=<%= cheaterPhone.phone %>&userId=<%= cheaterPhone.userId%>"
виправив

2023-11-07 23:39 UTC, OleksandrZhelihovskyi commented on views/pages/categories.ejs
>                                                  <a href="/forms/category/?id=<%= category.id %>&title=<%= category.title %>"
виправив

2023-11-07 23:39 UTC, OleksandrZhelihovskyi commented on views/templates/sidebar.ejs
> +            <span class="ms-1 font-weight-bold text-white">Login page</span>
виправив

2023-11-08 00:10 UTC, OleksandrZhelihovskyi commented on models/topic.js
> +        Topic.belongsToMany(models.User, {
вже пофіксив

2023-11-08 10:52 UTC, VitaliyBogdanuk requested changes

2023-11-08 10:52 UTC, VitaliyBogdanuk commented on controllers/cheaterPhoneController.js
> +        res.status(500).json({ message: err.message });
ви перевіряли цей метод з адмінки?
Що відбувається у разі помилки?

2023-11-08 10:57 UTC, OleksandrZhelihovskyi commented on controllers/cheaterPhoneController.js
> +        res.status(500).json({ message: err.message });
виведе JSON на екран

2023-11-08 10:58 UTC, VitaliyBogdanuk commented on controllers/cheaterPhoneController.js
> +        res.status(500).json({ message: err.message });
це ж адмінка, чому не поверне назад на сторінку і не покаже помилку в попапі?

2023-11-08 11:01 UTC, VitaliyBogdanuk commented on controllers/cheaterPhoneController.js
> +        res.status(500).json({ message: err.message });
у вас це було
 res.render('pages/form_cheaterPhone', {
            error: err
        });
а ви вирішили показувати json? поясніть рішення

2023-11-08 11:08 UTC, VitaliyBogdanuk commented on controllers/cheaterPhoneController.js
> +        res.status(500).json({ message: err.message });
@OleksandrZhelihovskyi

2023-11-08 11:12 UTC, OleksandrZhelihovskyi commented on controllers/cheaterPhoneController.js
> +        res.status(500).json({ message: err.message });
// req.flash('error', 'Creation failed: ' + err.message); // TODO. Ну тут же написано TODO. Не всі обробники помилок ще корректно описані. Я ж робив update. Це буде пізніше

2023-11-08 11:30 UTC, VitaliyBogdanuk commented on controllers/cheaterPhoneController.js
> +        res.status(500).json({ message: err.message });
Так в чому проблема, там є якісь помилки чи що ламає попередній код?
доробіть

2023-11-08 11:48 UTC, OleksandrZhelihovskyi commented on controllers/cheaterPhoneController.js
> +        res.status(500).json({ message: err.message });
повернув назад як було. Ніби має працювати той рендер

2023-11-08 12:33 UTC, VitaliyBogdanuk commented on controllers/cheaterPhoneController.js
> +        res.status(500).json({ message: err.message });
що значить ніби має працювати? ви перевірили?

2023-11-08 13:05 UTC, VitaliyBogdanuk requested changes

2023-11-08 13:05 UTC, VitaliyBogdanuk commented on controllers/cheaterPhoneController.js
> +            cheaterPhonesList: await exports.getCheaterPhones(),
Поясніть, от ви повертаєтесь назад на форму створення/редагування.
Навіщо ви передаєте всіх чітерів?
Вам не здається що було б логічніше повертати на вьюху ті данні які юзер намагався заповнити але десь допустив помилку, для того щоб він не вводив все з нуля?

2023-11-08 15:56 UTC, OleksandrZhelihovskyi commented on controllers/cheaterPhoneController.js
> +            cheaterPhonesList: await exports.getCheaterPhones(),
заберу його. Я заплутався вже просто. А таке реалізувати можна спробувати

2023-11-08 17:39 UTC, merged