Task/moderation info
VitaliyBogdanuk/swidler-quiz-app-server pull request #125
Opened 2023-11-22 15:30 UTC by OleksandrZhelihovskyi

moderation created

2023-11-23 10:28 UTC, VitaliyBogdanuk requested changes

2023-11-23 15:14 UTC, OleksandrZhelihovskyi commented on public/assets/css/material-dashboard.css
> +.modal {z-index: 2000;
який чат гпт? Це шаблон

2023-11-23 15:15 UTC, OleksandrZhelihovskyi commented on public/assets/css/material-dashboard.css
> +#myImg:hover {opacity: 0.7;}
це не я це готове рішення було. Перейменую

2023-11-23 15:16 UTC, OleksandrZhelihovskyi commented on public/assets/css/material-dashboard.css
> +    //max-width: 75%;
це шось теж з шаблона - подивлюся

2023-11-27 18:44 UTC, OleksandrZhelihovskyi commented on controllers/moderationController.js
> +        console.log(11)
fixed

2023-11-27 22:34 UTC, OleksandrZhelihovskyi commented on public/assets/css/material-dashboard.css
> +  add browser prefixes**/
виправив

2023-11-27 22:38 UTC, OleksandrZhelihovskyi commented on public/assets/css/material-dashboard.css
> +    //max-width: 75%;
виправив

2023-12-01 19:06 UTC, merged