Task/create data forms achievements topics
VitaliyBogdanuk/swidler-quiz-app-server pull request #39
Opened 2023-10-17 15:21 UTC by OleksandrZhelihovskyi

I've added forms for achievements and topics creating

2023-10-17 22:10 UTC, VitaliyBogdanuk requested changes
Please check all names and titles inside templates. They should be in one style and have sense

2023-10-17 22:10 UTC, VitaliyBogdanuk commented on views/pages/form_achievements.ejs
> +	<%- include('../templates/navbar', {breadcrumbs: 'Achievements' }); -%>
Achievements -> Create achievement

2023-10-17 22:10 UTC, VitaliyBogdanuk commented on routes/index.js
> +router.get('/forms/achievements', ensureAuthenticated, async (req, res) => {
achievement

2023-10-17 22:10 UTC, VitaliyBogdanuk commented on controllers/topicController.js
> +    try {//console.log(req)
Remove console.log

2023-10-17 22:10 UTC, VitaliyBogdanuk commented on views/pages/form_achievements.ejs
> +							<h6 class="text-white text-capitalize ps-3">Create Category</h6>
Create achievement

2023-10-17 22:10 UTC, VitaliyBogdanuk commented on views/pages/form_topics.ejs
> +	<%- include('../templates/navbar', {breadcrumbs: 'Topics' }); -%>
Create topic

2023-10-17 22:10 UTC, VitaliyBogdanuk commented on views/pages/form_topics.ejs
> +								<h4 class="font-weight-bolder">Enter an achievement name</h4>
Topic name

2023-10-18 11:09 UTC, OleksandrZhelihovskyi commented on views/pages/form_achievements.ejs
> +	<%- include('../templates/navbar', {breadcrumbs: 'Achievements' }); -%>
fixed

2023-10-18 11:24 UTC, OleksandrZhelihovskyi commented on routes/index.js
> +router.get('/forms/achievements', ensureAuthenticated, async (req, res) => {
fixed

2023-10-18 11:25 UTC, OleksandrZhelihovskyi commented on controllers/topicController.js
> +    try {//console.log(req)
fixed

2023-10-18 11:25 UTC, OleksandrZhelihovskyi commented on views/pages/form_achievements.ejs
> +							<h6 class="text-white text-capitalize ps-3">Create Category</h6>
fixed

2023-10-18 11:27 UTC, OleksandrZhelihovskyi commented on views/pages/form_topics.ejs
> +	<%- include('../templates/navbar', {breadcrumbs: 'Topics' }); -%>
fixed

2023-10-18 11:27 UTC, OleksandrZhelihovskyi commented on views/pages/form_topics.ejs
> +								<h4 class="font-weight-bolder">Enter an achievement name</h4>
fixed

2023-10-18 11:40 UTC, VitaliyBogdanuk requested changes

2023-10-18 11:40 UTC, VitaliyBogdanuk commented on views/pages/form_achievements.ejs
> +<%- include('../templates/sidebar', {view: 'Create achievements' }); -%>
<%- include('../templates/sidebar', {view: 'Create achievements' }); -%>
це передає в сайдбар який елемент меню підсвітити як вибраний, в нас не має в меню «Create achievements» тому залишіть просто «Аchievements» так як ця форма відноситься до цього розділу.

2023-10-18 11:40 UTC, VitaliyBogdanuk commented on views/pages/form_achievements.ejs
> +								<h4 class="font-weight-bolder">Enter an achievement name</h4>
<h4 class="font-weight-bolder">Enter an achievement name</h4>
Це хедер для нашої форми, в ачівках є не тільки поле назви а й інші, тому варто його прописати як "Fill in achievement data"

2023-10-18 11:40 UTC, VitaliyBogdanuk commented on views/pages/form_topics.ejs
> +<%- include('../templates/sidebar', {view: 'Create topic' }); -%>
<%- include('../templates/sidebar', {view: 'Create topic' }); -%>
це передає в сайдбар який елемент меню підсвітити як вибраний, в нас не має в меню «Create topic» тому залишіть просто «Topics» так як ця форма відноситься до цього розділу.

2023-10-18 11:40 UTC, VitaliyBogdanuk commented on views/pages/form_achievements.ejs
> +	<%- include('../templates/navbar', {breadcrumbs: 'Create achievements' }); -%>
Змініть Create achievements на Create achievement, використовуйте назви в однині, в даному випадку ви не створюєте багато сутностей одночасно

2023-10-18 11:40 UTC, VitaliyBogdanuk commented on views/pages/form_topics.ejs
> +								<h4 class="font-weight-bolder">Enter a topic name</h4>
Змініть Enter a topic name на Fill in topic data

2023-10-18 11:51 UTC, OleksandrZhelihovskyi commented on views/pages/form_achievements.ejs
> +<%- include('../templates/sidebar', {view: 'Create achievements' }); -%>
виправив

2023-10-18 11:51 UTC, OleksandrZhelihovskyi commented on views/pages/form_achievements.ejs
> +								<h4 class="font-weight-bolder">Enter an achievement name</h4>
виправив

2023-10-18 11:51 UTC, OleksandrZhelihovskyi commented on views/pages/form_topics.ejs
> +<%- include('../templates/sidebar', {view: 'Create topic' }); -%>
виправив

2023-10-18 11:51 UTC, OleksandrZhelihovskyi commented on views/pages/form_achievements.ejs
> +	<%- include('../templates/navbar', {breadcrumbs: 'Create achievements' }); -%>
виправив

2023-10-18 11:51 UTC, OleksandrZhelihovskyi commented on views/pages/form_topics.ejs
> +								<h4 class="font-weight-bolder">Enter a topic name</h4>
виправив

2023-10-18 12:12 UTC, merged